<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            // United States
            ['country_code' => 'USA', 'name' => 'New York'],
            ['country_code' => 'USA', 'name' => 'Los Angeles'],
            ['country_code' => 'USA', 'name' => 'Chicago'],
            ['country_code' => 'USA', 'name' => 'Houston'],
            ['country_code' => 'USA', 'name' => 'Phoenix'],
            ['country_code' => 'USA', 'name' => 'Philadelphia'],
            ['country_code' => 'USA', 'name' => 'San Antonio'],
            ['country_code' => 'USA', 'name' => 'San Diego'],
            ['country_code' => 'USA', 'name' => 'Dallas'],
            ['country_code' => 'USA', 'name' => 'San Jose'],

            // United Kingdom
            ['country_code' => 'GBR', 'name' => 'London'],
            ['country_code' => 'GBR', 'name' => 'Manchester'],
            ['country_code' => 'GBR', 'name' => 'Birmingham'],
            ['country_code' => 'GBR', 'name' => 'Liverpool'],
            ['country_code' => 'GBR', 'name' => 'Glasgow'],
            ['country_code' => 'GBR', 'name' => 'Edinburgh'],
            ['country_code' => 'GBR', 'name' => 'Bristol'],
            ['country_code' => 'GBR', 'name' => 'Leeds'],
            ['country_code' => 'GBR', 'name' => 'Sheffield'],
            ['country_code' => 'GBR', 'name' => 'Newcastle'],

            // Canada
            ['country_code' => 'CAN', 'name' => 'Toronto'],
            ['country_code' => 'CAN', 'name' => 'Vancouver'],
            ['country_code' => 'CAN', 'name' => 'Montreal'],
            ['country_code' => 'CAN', 'name' => 'Calgary'],
            ['country_code' => 'CAN', 'name' => 'Edmonton'],
            ['country_code' => 'CAN', 'name' => 'Ottawa'],
            ['country_code' => 'CAN', 'name' => 'Winnipeg'],
            ['country_code' => 'CAN', 'name' => 'Quebec City'],
            ['country_code' => 'CAN', 'name' => 'Hamilton'],
            ['country_code' => 'CAN', 'name' => 'Kitchener'],

            // Australia
            ['country_code' => 'AUS', 'name' => 'Sydney'],
            ['country_code' => 'AUS', 'name' => 'Melbourne'],
            ['country_code' => 'AUS', 'name' => 'Brisbane'],
            ['country_code' => 'AUS', 'name' => 'Perth'],
            ['country_code' => 'AUS', 'name' => 'Adelaide'],
            ['country_code' => 'AUS', 'name' => 'Gold Coast'],
            ['country_code' => 'AUS', 'name' => 'Canberra'],
            ['country_code' => 'AUS', 'name' => 'Newcastle'],
            ['country_code' => 'AUS', 'name' => 'Central Coast'],
            ['country_code' => 'AUS', 'name' => 'Wollongong'],

            // Germany
            ['country_code' => 'DEU', 'name' => 'Berlin'],
            ['country_code' => 'DEU', 'name' => 'Hamburg'],
            ['country_code' => 'DEU', 'name' => 'Munich'],
            ['country_code' => 'DEU', 'name' => 'Cologne'],
            ['country_code' => 'DEU', 'name' => 'Frankfurt'],
            ['country_code' => 'DEU', 'name' => 'Stuttgart'],
            ['country_code' => 'DEU', 'name' => 'Düsseldorf'],
            ['country_code' => 'DEU', 'name' => 'Dortmund'],
            ['country_code' => 'DEU', 'name' => 'Essen'],
            ['country_code' => 'DEU', 'name' => 'Leipzig'],

            // France
            ['country_code' => 'FRA', 'name' => 'Paris'],
            ['country_code' => 'FRA', 'name' => 'Marseille'],
            ['country_code' => 'FRA', 'name' => 'Lyon'],
            ['country_code' => 'FRA', 'name' => 'Toulouse'],
            ['country_code' => 'FRA', 'name' => 'Nice'],
            ['country_code' => 'FRA', 'name' => 'Nantes'],
            ['country_code' => 'FRA', 'name' => 'Strasbourg'],
            ['country_code' => 'FRA', 'name' => 'Montpellier'],
            ['country_code' => 'FRA', 'name' => 'Bordeaux'],
            ['country_code' => 'FRA', 'name' => 'Lille'],

            // Italy
            ['country_code' => 'ITA', 'name' => 'Rome'],
            ['country_code' => 'ITA', 'name' => 'Milan'],
            ['country_code' => 'ITA', 'name' => 'Naples'],
            ['country_code' => 'ITA', 'name' => 'Turin'],
            ['country_code' => 'ITA', 'name' => 'Palermo'],
            ['country_code' => 'ITA', 'name' => 'Genoa'],
            ['country_code' => 'ITA', 'name' => 'Bologna'],
            ['country_code' => 'ITA', 'name' => 'Florence'],
            ['country_code' => 'ITA', 'name' => 'Bari'],
            ['country_code' => 'ITA', 'name' => 'Catania'],

            // Spain
            ['country_code' => 'ESP', 'name' => 'Madrid'],
            ['country_code' => 'ESP', 'name' => 'Barcelona'],
            ['country_code' => 'ESP', 'name' => 'Valencia'],
            ['country_code' => 'ESP', 'name' => 'Seville'],
            ['country_code' => 'ESP', 'name' => 'Zaragoza'],
            ['country_code' => 'ESP', 'name' => 'Málaga'],
            ['country_code' => 'ESP', 'name' => 'Murcia'],
            ['country_code' => 'ESP', 'name' => 'Palma'],
            ['country_code' => 'ESP', 'name' => 'Las Palmas de Gran Canaria'],
            ['country_code' => 'ESP', 'name' => 'Bilbao'],

            // Netherlands
            ['country_code' => 'NLD', 'name' => 'Amsterdam'],
            ['country_code' => 'NLD', 'name' => 'Rotterdam'],
            ['country_code' => 'NLD', 'name' => 'The Hague'],
            ['country_code' => 'NLD', 'name' => 'Utrecht'],
            ['country_code' => 'NLD', 'name' => 'Eindhoven'],
            ['country_code' => 'NLD', 'name' => 'Tilburg'],
            ['country_code' => 'NLD', 'name' => 'Groningen'],
            ['country_code' => 'NLD', 'name' => 'Almere'],
            ['country_code' => 'NLD', 'name' => 'Breda'],
            ['country_code' => 'NLD', 'name' => 'Nijmegen'],

            // Belgium
            ['country_code' => 'BEL', 'name' => 'Brussels'],
            ['country_code' => 'BEL', 'name' => 'Antwerp'],
            ['country_code' => 'BEL', 'name' => 'Ghent'],
            ['country_code' => 'BEL', 'name' => 'Charleroi'],
            ['country_code' => 'BEL', 'name' => 'Liège'],
            ['country_code' => 'BEL', 'name' => 'Bruges'],
            ['country_code' => 'BEL', 'name' => 'Namur'],
            ['country_code' => 'BEL', 'name' => 'Leuven'],
            ['country_code' => 'BEL', 'name' => 'Mons'],
            ['country_code' => 'BEL', 'name' => 'Aalst'],

            // Brazil
            ['country_code' => 'BRA', 'name' => 'São Paulo'],
            ['country_code' => 'BRA', 'name' => 'Rio de Janeiro'],
            ['country_code' => 'BRA', 'name' => 'Brasília'],
            ['country_code' => 'BRA', 'name' => 'Salvador'],
            ['country_code' => 'BRA', 'name' => 'Fortaleza'],
            ['country_code' => 'BRA', 'name' => 'Belo Horizonte'],
            ['country_code' => 'BRA', 'name' => 'Manaus'],
            ['country_code' => 'BRA', 'name' => 'Curitiba'],
            ['country_code' => 'BRA', 'name' => 'Recife'],
            ['country_code' => 'BRA', 'name' => 'Porto Alegre'],

            // Mexico
            ['country_code' => 'MEX', 'name' => 'Mexico City'],
            ['country_code' => 'MEX', 'name' => 'Guadalajara'],
            ['country_code' => 'MEX', 'name' => 'Monterrey'],
            ['country_code' => 'MEX', 'name' => 'Puebla'],
            ['country_code' => 'MEX', 'name' => 'Tijuana'],
            ['country_code' => 'MEX', 'name' => 'León'],
            ['country_code' => 'MEX', 'name' => 'Juárez'],
            ['country_code' => 'MEX', 'name' => 'Torreón'],
            ['country_code' => 'MEX', 'name' => 'Querétaro'],
            ['country_code' => 'MEX', 'name' => 'Mérida'],

            // Argentina
            ['country_code' => 'ARG', 'name' => 'Buenos Aires'],
            ['country_code' => 'ARG', 'name' => 'Córdoba'],
            ['country_code' => 'ARG', 'name' => 'Rosario'],
            ['country_code' => 'ARG', 'name' => 'Mendoza'],
            ['country_code' => 'ARG', 'name' => 'San Miguel de Tucumán'],
            ['country_code' => 'ARG', 'name' => 'La Plata'],
            ['country_code' => 'ARG', 'name' => 'Mar del Plata'],
            ['country_code' => 'ARG', 'name' => 'Salta'],
            ['country_code' => 'ARG', 'name' => 'Santa Fe'],
            ['country_code' => 'ARG', 'name' => 'San Juan'],

            // Chile
            ['country_code' => 'CHL', 'name' => 'Santiago'],
            ['country_code' => 'CHL', 'name' => 'Puente Alto'],
            ['country_code' => 'CHL', 'name' => 'Antofagasta'],
            ['country_code' => 'CHL', 'name' => 'Viña del Mar'],
            ['country_code' => 'CHL', 'name' => 'Valparaíso'],
            ['country_code' => 'CHL', 'name' => 'Talcahuano'],
            ['country_code' => 'CHL', 'name' => 'San Bernardo'],
            ['country_code' => 'CHL', 'name' => 'Temuco'],
            ['country_code' => 'CHL', 'name' => 'Iquique'],
            ['country_code' => 'CHL', 'name' => 'Concepción'],

            // Colombia
            ['country_code' => 'COL', 'name' => 'Bogotá'],
            ['country_code' => 'COL', 'name' => 'Medellín'],
            ['country_code' => 'COL', 'name' => 'Cali'],
            ['country_code' => 'COL', 'name' => 'Barranquilla'],
            ['country_code' => 'COL', 'name' => 'Cartagena'],
            ['country_code' => 'COL', 'name' => 'Cúcuta'],
            ['country_code' => 'COL', 'name' => 'Bucaramanga'],
            ['country_code' => 'COL', 'name' => 'Pereira'],
            ['country_code' => 'COL', 'name' => 'Santa Marta'],
            ['country_code' => 'COL', 'name' => 'Ibagué'],

            // Peru
            ['country_code' => 'PER', 'name' => 'Lima'],
            ['country_code' => 'PER', 'name' => 'Arequipa'],
            ['country_code' => 'PER', 'name' => 'Trujillo'],
            ['country_code' => 'PER', 'name' => 'Chiclayo'],
            ['country_code' => 'PER', 'name' => 'Piura'],
            ['country_code' => 'PER', 'name' => 'Cusco'],
            ['country_code' => 'PER', 'name' => 'Chimbote'],
            ['country_code' => 'PER', 'name' => 'Huancayo'],
            ['country_code' => 'PER', 'name' => 'Iquitos'],
            ['country_code' => 'PER', 'name' => 'Pucallpa'],

            // Venezuela
            ['country_code' => 'VEN', 'name' => 'Caracas'],
            ['country_code' => 'VEN', 'name' => 'Maracaibo'],
            ['country_code' => 'VEN', 'name' => 'Maracay'],
            ['country_code' => 'VEN', 'name' => 'Valencia'],
            ['country_code' => 'VEN', 'name' => 'Barquisimeto'],
            ['country_code' => 'VEN', 'name' => 'Ciudad Guayana'],
            ['country_code' => 'VEN', 'name' => 'Barcelona'],
            ['country_code' => 'VEN', 'name' => 'Maturín'],
            ['country_code' => 'VEN', 'name' => 'San Cristóbal'],
            ['country_code' => 'VEN', 'name' => 'Cumaná'],

            // Ecuador
            ['country_code' => 'ECU', 'name' => 'Guayaquil'],
            ['country_code' => 'ECU', 'name' => 'Quito'],
            ['country_code' => 'ECU', 'name' => 'Cuenca'],
            ['country_code' => 'ECU', 'name' => 'Santo Domingo'],
            ['country_code' => 'ECU', 'name' => 'Machala'],
            ['country_code' => 'ECU', 'name' => 'Durán'],
            ['country_code' => 'ECU', 'name' => 'Manta'],
            ['country_code' => 'ECU', 'name' => 'Portoviejo'],
            ['country_code' => 'ECU', 'name' => 'Ambato'],
            ['country_code' => 'ECU', 'name' => 'Riobamba'],

            // Bolivia
            ['country_code' => 'BOL', 'name' => 'Santa Cruz de la Sierra'],
            ['country_code' => 'BOL', 'name' => 'La Paz'],
            ['country_code' => 'BOL', 'name' => 'El Alto'],
            ['country_code' => 'BOL', 'name' => 'Cochabamba'],
            ['country_code' => 'BOL', 'name' => 'Oruro'],
            ['country_code' => 'BOL', 'name' => 'Sucre'],
            ['country_code' => 'BOL', 'name' => 'Tarija'],
            ['country_code' => 'BOL', 'name' => 'Potosí'],
            ['country_code' => 'BOL', 'name' => 'Sacaba'],
            ['country_code' => 'BOL', 'name' => 'Montero'],

            // Paraguay
            ['country_code' => 'PRY', 'name' => 'Asunción'],
            ['country_code' => 'PRY', 'name' => 'Ciudad del Este'],
            ['country_code' => 'PRY', 'name' => 'San Lorenzo'],
            ['country_code' => 'PRY', 'name' => 'Luque'],
            ['country_code' => 'PRY', 'name' => 'Capiatá'],
            ['country_code' => 'PRY', 'name' => 'Lambaré'],
            ['country_code' => 'PRY', 'name' => 'Fernando de la Mora'],
            ['country_code' => 'PRY', 'name' => 'Limpio'],
            ['country_code' => 'PRY', 'name' => 'Ñemby'],
            ['country_code' => 'PRY', 'name' => 'Encarnación'],

            // Uruguay
            ['country_code' => 'URY', 'name' => 'Montevideo'],
            ['country_code' => 'URY', 'name' => 'Salto'],
            ['country_code' => 'URY', 'name' => 'Ciudad de la Costa'],
            ['country_code' => 'URY', 'name' => 'Paysandú'],
            ['country_code' => 'URY', 'name' => 'Las Piedras'],
            ['country_code' => 'URY', 'name' => 'Rivera'],
            ['country_code' => 'URY', 'name' => 'Maldonado'],
            ['country_code' => 'URY', 'name' => 'Tacuarembó'],
            ['country_code' => 'URY', 'name' => 'Melo'],
            ['country_code' => 'URY', 'name' => 'Mercedes'],

            // Japan
            ['country_code' => 'JPN', 'name' => 'Tokyo'],
            ['country_code' => 'JPN', 'name' => 'Yokohama'],
            ['country_code' => 'JPN', 'name' => 'Osaka'],
            ['country_code' => 'JPN', 'name' => 'Nagoya'],
            ['country_code' => 'JPN', 'name' => 'Sapporo'],
            ['country_code' => 'JPN', 'name' => 'Fukuoka'],
            ['country_code' => 'JPN', 'name' => 'Kobe'],
            ['country_code' => 'JPN', 'name' => 'Kawasaki'],
            ['country_code' => 'JPN', 'name' => 'Kyoto'],
            ['country_code' => 'JPN', 'name' => 'Saitama'],

            // China
            ['country_code' => 'CHN', 'name' => 'Shanghai'],
            ['country_code' => 'CHN', 'name' => 'Beijing'],
            ['country_code' => 'CHN', 'name' => 'Guangzhou'],
            ['country_code' => 'CHN', 'name' => 'Shenzhen'],
            ['country_code' => 'CHN', 'name' => 'Tianjin'],
            ['country_code' => 'CHN', 'name' => 'Wuhan'],
            ['country_code' => 'CHN', 'name' => 'Dongguan'],
            ['country_code' => 'CHN', 'name' => 'Chengdu'],
            ['country_code' => 'CHN', 'name' => 'Nanjing'],
            ['country_code' => 'CHN', 'name' => 'Xi\'an'],

            // India
            ['country_code' => 'IND', 'name' => 'Mumbai'],
            ['country_code' => 'IND', 'name' => 'Delhi'],
            ['country_code' => 'IND', 'name' => 'Bangalore'],
            ['country_code' => 'IND', 'name' => 'Hyderabad'],
            ['country_code' => 'IND', 'name' => 'Ahmedabad'],
            ['country_code' => 'IND', 'name' => 'Chennai'],
            ['country_code' => 'IND', 'name' => 'Kolkata'],
            ['country_code' => 'IND', 'name' => 'Surat'],
            ['country_code' => 'IND', 'name' => 'Pune'],
            ['country_code' => 'IND', 'name' => 'Jaipur'],

            // South Korea
            ['country_code' => 'KOR', 'name' => 'Seoul'],
            ['country_code' => 'KOR', 'name' => 'Busan'],
            ['country_code' => 'KOR', 'name' => 'Incheon'],
            ['country_code' => 'KOR', 'name' => 'Daegu'],
            ['country_code' => 'KOR', 'name' => 'Daejeon'],
            ['country_code' => 'KOR', 'name' => 'Gwangju'],
            ['country_code' => 'KOR', 'name' => 'Suwon'],
            ['country_code' => 'KOR', 'name' => 'Ulsan'],
            ['country_code' => 'KOR', 'name' => 'Changwon'],
            ['country_code' => 'KOR', 'name' => 'Seongnam'],

            // Russia
            ['country_code' => 'RUS', 'name' => 'Moscow'],
            ['country_code' => 'RUS', 'name' => 'Saint Petersburg'],
            ['country_code' => 'RUS', 'name' => 'Novosibirsk'],
            ['country_code' => 'RUS', 'name' => 'Yekaterinburg'],
            ['country_code' => 'RUS', 'name' => 'Nizhny Novgorod'],
            ['country_code' => 'RUS', 'name' => 'Kazan'],
            ['country_code' => 'RUS', 'name' => 'Chelyabinsk'],
            ['country_code' => 'RUS', 'name' => 'Omsk'],
            ['country_code' => 'RUS', 'name' => 'Samara'],
            ['country_code' => 'RUS', 'name' => 'Rostov-on-Don'],

            // Ukraine
            ['country_code' => 'UKR', 'name' => 'Kyiv'],
            ['country_code' => 'UKR', 'name' => 'Kharkiv'],
            ['country_code' => 'UKR', 'name' => 'Odesa'],
            ['country_code' => 'UKR', 'name' => 'Dnipro'],
            ['country_code' => 'UKR', 'name' => 'Donetsk'],
            ['country_code' => 'UKR', 'name' => 'Zaporizhzhia'],
            ['country_code' => 'UKR', 'name' => 'Lviv'],
            ['country_code' => 'UKR', 'name' => 'Kryvyi Rih'],
            ['country_code' => 'UKR', 'name' => 'Mykolaiv'],
            ['country_code' => 'UKR', 'name' => 'Mariupol'],

            // Poland
            ['country_code' => 'POL', 'name' => 'Warsaw'],
            ['country_code' => 'POL', 'name' => 'Kraków'],
            ['country_code' => 'POL', 'name' => 'Łódź'],
            ['country_code' => 'POL', 'name' => 'Wrocław'],
            ['country_code' => 'POL', 'name' => 'Poznań'],
            ['country_code' => 'POL', 'name' => 'Gdańsk'],
            ['country_code' => 'POL', 'name' => 'Szczecin'],
            ['country_code' => 'POL', 'name' => 'Bydgoszcz'],
            ['country_code' => 'POL', 'name' => 'Lublin'],
            ['country_code' => 'POL', 'name' => 'Katowice'],

            // Czech Republic
            ['country_code' => 'CZE', 'name' => 'Prague'],
            ['country_code' => 'CZE', 'name' => 'Brno'],
            ['country_code' => 'CZE', 'name' => 'Ostrava'],
            ['country_code' => 'CZE', 'name' => 'Plzeň'],
            ['country_code' => 'CZE', 'name' => 'Liberec'],
            ['country_code' => 'CZE', 'name' => 'Olomouc'],
            ['country_code' => 'CZE', 'name' => 'Ústí nad Labem'],
            ['country_code' => 'CZE', 'name' => 'České Budějovice'],
            ['country_code' => 'CZE', 'name' => 'Hradec Králové'],
            ['country_code' => 'CZE', 'name' => 'Pardubice'],

            // Hungary
            ['country_code' => 'HUN', 'name' => 'Budapest'],
            ['country_code' => 'HUN', 'name' => 'Debrecen'],
            ['country_code' => 'HUN', 'name' => 'Szeged'],
            ['country_code' => 'HUN', 'name' => 'Miskolc'],
            ['country_code' => 'HUN', 'name' => 'Pécs'],
            ['country_code' => 'HUN', 'name' => 'Győr'],
            ['country_code' => 'HUN', 'name' => 'Nyíregyháza'],
            ['country_code' => 'HUN', 'name' => 'Kecskemét'],
            ['country_code' => 'HUN', 'name' => 'Székesfehérvár'],
            ['country_code' => 'HUN', 'name' => 'Szombathely'],

            // Romania
            ['country_code' => 'ROU', 'name' => 'Bucharest'],
            ['country_code' => 'ROU', 'name' => 'Cluj-Napoca'],
            ['country_code' => 'ROU', 'name' => 'Timișoara'],
            ['country_code' => 'ROU', 'name' => 'Iași'],
            ['country_code' => 'ROU', 'name' => 'Constanța'],
            ['country_code' => 'ROU', 'name' => 'Craiova'],
            ['country_code' => 'ROU', 'name' => 'Brașov'],
            ['country_code' => 'ROU', 'name' => 'Galați'],
            ['country_code' => 'ROU', 'name' => 'Ploiești'],
            ['country_code' => 'ROU', 'name' => 'Oradea'],

            // Bulgaria
            ['country_code' => 'BGR', 'name' => 'Sofia'],
            ['country_code' => 'BGR', 'name' => 'Plovdiv'],
            ['country_code' => 'BGR', 'name' => 'Varna'],
            ['country_code' => 'BGR', 'name' => 'Burgas'],
            ['country_code' => 'BGR', 'name' => 'Ruse'],
            ['country_code' => 'BGR', 'name' => 'Stara Zagora'],
            ['country_code' => 'BGR', 'name' => 'Pleven'],
            ['country_code' => 'BGR', 'name' => 'Sliven'],
            ['country_code' => 'BGR', 'name' => 'Dobrich'],
            ['country_code' => 'BGR', 'name' => 'Shumen'],

            // Greece
            ['country_code' => 'GRC', 'name' => 'Athens'],
            ['country_code' => 'GRC', 'name' => 'Thessaloniki'],
            ['country_code' => 'GRC', 'name' => 'Patras'],
            ['country_code' => 'GRC', 'name' => 'Piraeus'],
            ['country_code' => 'GRC', 'name' => 'Larissa'],
            ['country_code' => 'GRC', 'name' => 'Heraklion'],
            ['country_code' => 'GRC', 'name' => 'Peristeri'],
            ['country_code' => 'GRC', 'name' => 'Kallithea'],
            ['country_code' => 'GRC', 'name' => 'Acharnes'],
            ['country_code' => 'GRC', 'name' => 'Kalamaria'],

            // Turkey
            ['country_code' => 'TUR', 'name' => 'Istanbul'],
            ['country_code' => 'TUR', 'name' => 'Ankara'],
            ['country_code' => 'TUR', 'name' => 'İzmir'],
            ['country_code' => 'TUR', 'name' => 'Bursa'],
            ['country_code' => 'TUR', 'name' => 'Adana'],
            ['country_code' => 'TUR', 'name' => 'Gaziantep'],
            ['country_code' => 'TUR', 'name' => 'Konya'],
            ['country_code' => 'TUR', 'name' => 'Antalya'],
            ['country_code' => 'TUR', 'name' => 'Kayseri'],
            ['country_code' => 'TUR', 'name' => 'Samsun'],

            // Egypt
            ['country_code' => 'EGY', 'name' => 'Cairo'],
            ['country_code' => 'EGY', 'name' => 'Alexandria'],
            ['country_code' => 'EGY', 'name' => 'Giza'],
            ['country_code' => 'EGY', 'name' => 'Shubra El-Kheima'],
            ['country_code' => 'EGY', 'name' => 'Port Said'],
            ['country_code' => 'EGY', 'name' => 'Suez'],
            ['country_code' => 'EGY', 'name' => 'Luxor'],
            ['country_code' => 'EGY', 'name' => 'Mansoura'],
            ['country_code' => 'EGY', 'name' => 'Tanta'],
            ['country_code' => 'EGY', 'name' => 'Asyut'],

            // South Africa
            ['country_code' => 'ZAF', 'name' => 'Johannesburg'],
            ['country_code' => 'ZAF', 'name' => 'Cape Town'],
            ['country_code' => 'ZAF', 'name' => 'Durban'],
            ['country_code' => 'ZAF', 'name' => 'Pretoria'],
            ['country_code' => 'ZAF', 'name' => 'Port Elizabeth'],
            ['country_code' => 'ZAF', 'name' => 'Bloemfontein'],
            ['country_code' => 'ZAF', 'name' => 'East London'],
            ['country_code' => 'ZAF', 'name' => 'Pietermaritzburg'],
            ['country_code' => 'ZAF', 'name' => 'Benoni'],
            ['country_code' => 'ZAF', 'name' => 'Tembisa'],

            // Nigeria
            ['country_code' => 'NGA', 'name' => 'Lagos'],
            ['country_code' => 'NGA', 'name' => 'Kano'],
            ['country_code' => 'NGA', 'name' => 'Ibadan'],
            ['country_code' => 'NGA', 'name' => 'Abuja'],
            ['country_code' => 'NGA', 'name' => 'Port Harcourt'],
            ['country_code' => 'NGA', 'name' => 'Benin City'],
            ['country_code' => 'NGA', 'name' => 'Kaduna'],
            ['country_code' => 'NGA', 'name' => 'Enugu'],
            ['country_code' => 'NGA', 'name' => 'Ilorin'],
            ['country_code' => 'NGA', 'name' => 'Abeokuta'],

            // Kenya
            ['country_code' => 'KEN', 'name' => 'Nairobi'],
            ['country_code' => 'KEN', 'name' => 'Mombasa'],
            ['country_code' => 'KEN', 'name' => 'Kisumu'],
            ['country_code' => 'KEN', 'name' => 'Nakuru'],
            ['country_code' => 'KEN', 'name' => 'Eldoret'],
            ['country_code' => 'KEN', 'name' => 'Kakamega'],
            ['country_code' => 'KEN', 'name' => 'Kitale'],
            ['country_code' => 'KEN', 'name' => 'Malindi'],
            ['country_code' => 'KEN', 'name' => 'Garissa'],
            ['country_code' => 'KEN', 'name' => 'Kisii'],

            // Ghana
            ['country_code' => 'GHA', 'name' => 'Accra'],
            ['country_code' => 'GHA', 'name' => 'Kumasi'],
            ['country_code' => 'GHA', 'name' => 'Tamale'],
            ['country_code' => 'GHA', 'name' => 'Takoradi'],
            ['country_code' => 'GHA', 'name' => 'Atsiaman'],
            ['country_code' => 'GHA', 'name' => 'Tema'],
            ['country_code' => 'GHA', 'name' => 'Cape Coast'],
            ['country_code' => 'GHA', 'name' => 'Obuasi'],
            ['country_code' => 'GHA', 'name' => 'Teshie'],
            ['country_code' => 'GHA', 'name' => 'Madina'],

            // Morocco
            ['country_code' => 'MAR', 'name' => 'Casablanca'],
            ['country_code' => 'MAR', 'name' => 'Rabat'],
            ['country_code' => 'MAR', 'name' => 'Fès'],
            ['country_code' => 'MAR', 'name' => 'Marrakech'],
            ['country_code' => 'MAR', 'name' => 'Salé'],
            ['country_code' => 'MAR', 'name' => 'Agadir'],
            ['country_code' => 'MAR', 'name' => 'Oujda'],
            ['country_code' => 'MAR', 'name' => 'Kenitra'],
            ['country_code' => 'MAR', 'name' => 'Tétouan'],
            ['country_code' => 'MAR', 'name' => 'Safi'],

            // Tunisia
            ['country_code' => 'TUN', 'name' => 'Tunis'],
            ['country_code' => 'TUN', 'name' => 'Sfax'],
            ['country_code' => 'TUN', 'name' => 'Sousse'],
            ['country_code' => 'TUN', 'name' => 'Ettadhamen'],
            ['country_code' => 'TUN', 'name' => 'Kairouan'],
            ['country_code' => 'TUN', 'name' => 'Bizerte'],
            ['country_code' => 'TUN', 'name' => 'Gabès'],
            ['country_code' => 'TUN', 'name' => 'Ariana'],
            ['country_code' => 'TUN', 'name' => 'Gafsa'],
            ['country_code' => 'TUN', 'name' => 'El Mourouj'],

            // Algeria
            ['country_code' => 'DZA', 'name' => 'Algiers'],
            ['country_code' => 'DZA', 'name' => 'Oran'],
            ['country_code' => 'DZA', 'name' => 'Constantine'],
            ['country_code' => 'DZA', 'name' => 'Annaba'],
            ['country_code' => 'DZA', 'name' => 'Blida'],
            ['country_code' => 'DZA', 'name' => 'Batna'],
            ['country_code' => 'DZA', 'name' => 'Djelfa'],
            ['country_code' => 'DZA', 'name' => 'Sétif'],
            ['country_code' => 'DZA', 'name' => 'Sidi Bel Abbès'],
            ['country_code' => 'DZA', 'name' => 'Biskra'],

            // Libya
            ['country_code' => 'LBY', 'name' => 'Tripoli'],
            ['country_code' => 'LBY', 'name' => 'Benghazi'],
            ['country_code' => 'LBY', 'name' => 'Misrata'],
            ['country_code' => 'LBY', 'name' => 'Tarhuna'],
            ['country_code' => 'LBY', 'name' => 'Al Khums'],
            ['country_code' => 'LBY', 'name' => 'Zawiya'],
            ['country_code' => 'LBY', 'name' => 'Ajdabiya'],
            ['country_code' => 'LBY', 'name' => 'Sabha'],
            ['country_code' => 'LBY', 'name' => 'Zliten'],
            ['country_code' => 'LBY', 'name' => 'Tobruk'],

            // Sudan
            ['country_code' => 'SDN', 'name' => 'Khartoum'],
            ['country_code' => 'SDN', 'name' => 'Omdurman'],
            ['country_code' => 'SDN', 'name' => 'Khartoum North'],
            ['country_code' => 'SDN', 'name' => 'Port Sudan'],
            ['country_code' => 'SDN', 'name' => 'Kassala'],
        ];

        foreach ($cities as $cityData) {
            $country = Country::where('code', $cityData['country_code'])->first();
            if ($country) {
                City::create([
                    'name' => $cityData['name'],
                    'country_id' => $country->id,
                ]);
            }
        }

        // Add capitals for all countries to ensure every country has at least one city
        $capitals = [
            'AFG' => 'Kabul',
            'ALB' => 'Tirana',
            'DZA' => 'Algiers',
            'ASM' => 'Pago Pago',
            'AND' => 'Andorra la Vella',
            'AGO' => 'Luanda',
            'AIA' => 'The Valley',
            'ATA' => 'N/A',
            'ATG' => 'Saint John\'s',
            'ARG' => 'Buenos Aires',
            'ARM' => 'Yerevan',
            'ABW' => 'Oranjestad',
            'AUS' => 'Canberra',
            'AUT' => 'Vienna',
            'AZE' => 'Baku',
            'BHS' => 'Nassau',
            'BHR' => 'Manama',
            'BGD' => 'Dhaka',
            'BRB' => 'Bridgetown',
            'BLR' => 'Minsk',
            'BEL' => 'Brussels',
            'BLZ' => 'Belmopan',
            'BEN' => 'Porto-Novo',
            'BMU' => 'Hamilton',
            'BTN' => 'Thimphu',
            'BOL' => 'Sucre',
            'BIH' => 'Sarajevo',
            'BWA' => 'Gaborone',
            'BVT' => 'N/A',
            'BRA' => 'Brasília',
            'IOT' => 'N/A',
            'BRN' => 'Bandar Seri Begawan',
            'BGR' => 'Sofia',
            'BFA' => 'Ouagadougou',
            'BDI' => 'Bujumbura',
            'KHM' => 'Phnom Penh',
            'CMR' => 'Yaoundé',
            'CAN' => 'Ottawa',
            'CPV' => 'Praia',
            'CYM' => 'George Town',
            'CAF' => 'Bangui',
            'TCD' => 'N\'Djamena',
            'CHL' => 'Santiago',
            'CHN' => 'Beijing',
            'CXR' => 'Flying Fish Cove',
            'CCK' => 'West Island',
            'COL' => 'Bogotá',
            'COM' => 'Moroni',
            'COG' => 'Brazzaville',
            'COD' => 'Kinshasa',
            'COK' => 'Avarua',
            'CRI' => 'San José',
            'CIV' => 'Yamoussoukro',
            'HRV' => 'Zagreb',
            'CUB' => 'Havana',
            'CYP' => 'Nicosia',
            'CZE' => 'Prague',
            'DNK' => 'Copenhagen',
            'DJI' => 'Djibouti',
            'DMA' => 'Roseau',
            'DOM' => 'Santo Domingo',
            'ECU' => 'Quito',
            'EGY' => 'Cairo',
            'SLV' => 'San Salvador',
            'GNQ' => 'Malabo',
            'ERI' => 'Asmara',
            'EST' => 'Tallinn',
            'ETH' => 'Addis Ababa',
            'FLK' => 'Stanley',
            'FRO' => 'Tórshavn',
            'FJI' => 'Suva',
            'FIN' => 'Helsinki',
            'FRA' => 'Paris',
            'GUF' => 'Cayenne',
            'PYF' => 'Papeete',
            'ATF' => 'Port-aux-Français',
            'GAB' => 'Libreville',
            'GMB' => 'Banjul',
            'GEO' => 'Tbilisi',
            'DEU' => 'Berlin',
            'GHA' => 'Accra',
            'GIB' => 'Gibraltar',
            'GRC' => 'Athens',
            'GRL' => 'Nuuk',
            'GRD' => 'Saint George\'s',
            'GLP' => 'Basse-Terre',
            'GUM' => 'Hagåtña',
            'GTM' => 'Guatemala City',
            'GGY' => 'Saint Peter Port',
            'GIN' => 'Conakry',
            'GNB' => 'Bissau',
            'GUY' => 'Georgetown',
            'HTI' => 'Port-au-Prince',
            'HMD' => 'N/A',
            'VAT' => 'Vatican City',
            'HND' => 'Tegucigalpa',
            'HKG' => 'Hong Kong',
            'HUN' => 'Budapest',
            'ISL' => 'Reykjavík',
            'IND' => 'New Delhi',
            'IDN' => 'Jakarta',
            'IRN' => 'Tehran',
            'IRQ' => 'Baghdad',
            'IRL' => 'Dublin',
            'IMN' => 'Douglas',
            'ISR' => 'Jerusalem',
            'ITA' => 'Rome',
            'JAM' => 'Kingston',
            'JPN' => 'Tokyo',
            'JEY' => 'Saint Helier',
            'JOR' => 'Amman',
            'KAZ' => 'Astana',
            'KEN' => 'Nairobi',
            'KIR' => 'Tarawa',
            'PRK' => 'Pyongyang',
            'KOR' => 'Seoul',
            'KWT' => 'Kuwait City',
            'KGZ' => 'Bishkek',
            'LAO' => 'Vientiane',
            'LVA' => 'Riga',
            'LBN' => 'Beirut',
            'LSO' => 'Maseru',
            'LBR' => 'Monrovia',
            'LBY' => 'Tripoli',
            'LIE' => 'Vaduz',
            'LTU' => 'Vilnius',
            'LUX' => 'Luxembourg',
            'MAC' => 'Macao',
            'MKD' => 'Skopje',
            'MDG' => 'Antananarivo',
            'MWI' => 'Lilongwe',
            'MYS' => 'Kuala Lumpur',
            'MDV' => 'Malé',
            'MLI' => 'Bamako',
            'MLT' => 'Valletta',
            'MHL' => 'Majuro',
            'MTQ' => 'Fort-de-France',
            'MRT' => 'Nouakchott',
            'MUS' => 'Port Louis',
            'MYT' => 'Mamoudzou',
            'MEX' => 'Mexico City',
            'FSM' => 'Palikir',
            'MDA' => 'Chișinău',
            'MCO' => 'Monaco',
            'MNG' => 'Ulaanbaatar',
            'MNE' => 'Podgorica',
            'MSR' => 'Plymouth',
            'MAR' => 'Rabat',
            'MOZ' => 'Maputo',
            'MMR' => 'Naypyidaw',
            'NAM' => 'Windhoek',
            'NRU' => 'Yaren',
            'NPL' => 'Kathmandu',
            'NLD' => 'Amsterdam',
            'ANT' => 'Willemstad',
            'NCL' => 'Nouméa',
            'NZL' => 'Wellington',
            'NIC' => 'Managua',
            'NER' => 'Niamey',
            'NGA' => 'Abuja',
            'NIU' => 'Alofi',
            'NFK' => 'Kingston',
            'MNP' => 'Saipan',
            'NOR' => 'Oslo',
            'OMN' => 'Muscat',
            'PAK' => 'Islamabad',
            'PLW' => 'Ngerulmud',
            'PSE' => 'Ramallah',
            'PAN' => 'Panama City',
            'PNG' => 'Port Moresby',
            'PRY' => 'Asunción',
            'PER' => 'Lima',
            'PHL' => 'Manila',
            'PCN' => 'Adamstown',
            'POL' => 'Warsaw',
            'PRT' => 'Lisbon',
            'PRI' => 'San Juan',
            'QAT' => 'Doha',
            'REU' => 'Saint-Denis',
            'ROU' => 'Bucharest',
            'RUS' => 'Moscow',
            'RWA' => 'Kigali',
            'BLM' => 'Gustavia',
            'SHN' => 'Jamestown',
            'KNA' => 'Basseterre',
            'LCA' => 'Castries',
            'MAF' => 'Marigot',
            'SPM' => 'Saint-Pierre',
            'VCT' => 'Kingstown',
            'WSM' => 'Apia',
            'SMR' => 'San Marino',
            'STP' => 'São Tomé',
            'SAU' => 'Riyadh',
            'SEN' => 'Dakar',
            'SRB' => 'Belgrade',
            'SYC' => 'Victoria',
            'SLE' => 'Freetown',
            'SGP' => 'Singapore',
            'SVK' => 'Bratislava',
            'SVN' => 'Ljubljana',
            'SLB' => 'Honiara',
            'SOM' => 'Mogadishu',
            'ZAF' => 'Pretoria',
            'SGS' => 'Grytviken',
            'SSD' => 'Juba',
            'ESP' => 'Madrid',
            'LKA' => 'Sri Jayawardenepura Kotte',
            'SDN' => 'Khartoum',
            'SUR' => 'Paramaribo',
            'SJM' => 'Longyearbyen',
            'SWZ' => 'Mbabane',
            'SWE' => 'Stockholm',
            'CHE' => 'Bern',
            'SYR' => 'Damascus',
            'TWN' => 'Taipei',
            'TJK' => 'Dushanbe',
            'TZA' => 'Dodoma',
            'THA' => 'Bangkok',
            'TLS' => 'Dili',
            'TGO' => 'Lomé',
            'TKL' => 'Nukunonu',
            'TON' => 'Nuku\'alofa',
            'TTO' => 'Port of Spain',
            'TUN' => 'Tunis',
            'TUR' => 'Ankara',
            'TKM' => 'Ashgabat',
            'TCA' => 'Cockburn Town',
            'TUV' => 'Funafuti',
            'UGA' => 'Kampala',
            'UKR' => 'Kyiv',
            'ARE' => 'Abu Dhabi',
            'GBR' => 'London',
            'USA' => 'Washington, D.C.',
            'URY' => 'Montevideo',
            'UZB' => 'Tashkent',
            'VUT' => 'Port Vila',
            'VEN' => 'Caracas',
            'VNM' => 'Hanoi',
            'VGB' => 'Road Town',
            'VIR' => 'Charlotte Amalie',
            'WLF' => 'Mata-Utu',
            'ESH' => 'El Aaiún',
            'YEM' => 'Sana\'a',
            'ZMB' => 'Lusaka',
            'ZWE' => 'Harare',
            'ALA' => 'Mariehamn',
            'CUW' => 'Willemstad',
            'GGY' => 'Saint Peter Port',
            'IMN' => 'Douglas',
            'JEY' => 'Saint Helier',
            'MAF' => 'Marigot',
            'MCO' => 'Monaco',
            'SMR' => 'San Marino',
            'VAT' => 'Vatican City',
        ];

        foreach ($capitals as $code => $capital) {
            $country = Country::where('code', $code)->first();
            if ($country && !$country->cities()->where('name', $capital)->exists()) {
                City::create([
                    'name' => $capital,
                    'country_id' => $country->id,
                ]);
            }
        }
    }
}
