<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'United States', 'code' => 'USA'],
            ['name' => 'United Kingdom', 'code' => 'GBR'],
            ['name' => 'Canada', 'code' => 'CAN'],
            ['name' => 'Australia', 'code' => 'AUS'],
            ['name' => 'Germany', 'code' => 'DEU'],
            ['name' => 'France', 'code' => 'FRA'],
            ['name' => 'Italy', 'code' => 'ITA'],
            ['name' => 'Spain', 'code' => 'ESP'],
            ['name' => 'Netherlands', 'code' => 'NLD'],
            ['name' => 'Belgium', 'code' => 'BEL'],
            ['name' => 'Brazil', 'code' => 'BRA'],
            ['name' => 'Mexico', 'code' => 'MEX'],
            ['name' => 'Argentina', 'code' => 'ARG'],
            ['name' => 'Chile', 'code' => 'CHL'],
            ['name' => 'Colombia', 'code' => 'COL'],
            ['name' => 'Peru', 'code' => 'PER'],
            ['name' => 'Venezuela', 'code' => 'VEN'],
            ['name' => 'Ecuador', 'code' => 'ECU'],
            ['name' => 'Bolivia', 'code' => 'BOL'],
            ['name' => 'Paraguay', 'code' => 'PRY'],
            ['name' => 'Uruguay', 'code' => 'URY'],
            ['name' => 'Japan', 'code' => 'JPN'],
            ['name' => 'China', 'code' => 'CHN'],
            ['name' => 'India', 'code' => 'IND'],
            ['name' => 'South Korea', 'code' => 'KOR'],
            ['name' => 'Russia', 'code' => 'RUS'],
            ['name' => 'Ukraine', 'code' => 'UKR'],
            ['name' => 'Poland', 'code' => 'POL'],
            ['name' => 'Czech Republic', 'code' => 'CZE'],
            ['name' => 'Hungary', 'code' => 'HUN'],
            ['name' => 'Romania', 'code' => 'ROU'],
            ['name' => 'Bulgaria', 'code' => 'BGR'],
            ['name' => 'Greece', 'code' => 'GRC'],
            ['name' => 'Turkey', 'code' => 'TUR'],
            ['name' => 'Egypt', 'code' => 'EGY'],
            ['name' => 'South Africa', 'code' => 'ZAF'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Morocco', 'code' => 'MAR'],
            ['name' => 'Tunisia', 'code' => 'TUN'],
            ['name' => 'Algeria', 'code' => 'DZA'],
            ['name' => 'Libya', 'code' => 'LBY'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Mozambique', 'code' => 'MOZ'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Namibia', 'code' => 'NAM'],
            ['name' => 'Botswana', 'code' => 'BWA'],
            ['name' => 'Swaziland', 'code' => 'SWZ'],
            ['name' => 'Lesotho', 'code' => 'LSO'],
            ['name' => 'Madagascar', 'code' => 'MDG'],
            ['name' => 'Mauritius', 'code' => 'MUS'],
            ['name' => 'Seychelles', 'code' => 'SYC'],
            ['name' => 'Comoros', 'code' => 'COM'],
            ['name' => 'Mayotte', 'code' => 'MYT'],
            ['name' => 'Réunion', 'code' => 'REU'],
            ['name' => 'Saudi Arabia', 'code' => 'SAU'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE'],
            ['name' => 'Qatar', 'code' => 'QAT'],
            ['name' => 'Kuwait', 'code' => 'KWT'],
            ['name' => 'Bahrain', 'code' => 'BHR'],
            ['name' => 'Oman', 'code' => 'OMN'],
            ['name' => 'Yemen', 'code' => 'YEM'],
            ['name' => 'Jordan', 'code' => 'JOR'],
            ['name' => 'Lebanon', 'code' => 'LBN'],
            ['name' => 'Syria', 'code' => 'SYR'],
            ['name' => 'Iraq', 'code' => 'IRQ'],
            ['name' => 'Iran', 'code' => 'IRN'],
            ['name' => 'Afghanistan', 'code' => 'AFG'],
            ['name' => 'Pakistan', 'code' => 'PAK'],
            ['name' => 'Bangladesh', 'code' => 'BGD'],
            ['name' => 'Sri Lanka', 'code' => 'LKA'],
            ['name' => 'Nepal', 'code' => 'NPL'],
            ['name' => 'Bhutan', 'code' => 'BTN'],
            ['name' => 'Maldives', 'code' => 'MDV'],
            ['name' => 'Myanmar', 'code' => 'MMR'],
            ['name' => 'Thailand', 'code' => 'THA'],
            ['name' => 'Cambodia', 'code' => 'KHM'],
            ['name' => 'Laos', 'code' => 'LAO'],
            ['name' => 'Vietnam', 'code' => 'VNM'],
            ['name' => 'Malaysia', 'code' => 'MYS'],
            ['name' => 'Singapore', 'code' => 'SGP'],
            ['name' => 'Indonesia', 'code' => 'IDN'],
            ['name' => 'Philippines', 'code' => 'PHL'],
            ['name' => 'Brunei', 'code' => 'BRN'],
            ['name' => 'East Timor', 'code' => 'TLS'],
            ['name' => 'Papua New Guinea', 'code' => 'PNG'],
            ['name' => 'Solomon Islands', 'code' => 'SLB'],
            ['name' => 'Vanuatu', 'code' => 'VUT'],
            ['name' => 'Fiji', 'code' => 'FJI'],
            ['name' => 'Samoa', 'code' => 'WSM'],
            ['name' => 'Tonga', 'code' => 'TON'],
            ['name' => 'Tuvalu', 'code' => 'TUV'],
            ['name' => 'Kiribati', 'code' => 'KIR'],
            ['name' => 'Marshall Islands', 'code' => 'MHL'],
            ['name' => 'Micronesia', 'code' => 'FSM'],
            ['name' => 'Palau', 'code' => 'PLW'],
            ['name' => 'Nauru', 'code' => 'NRU'],
            ['name' => 'New Zealand', 'code' => 'NZL'],
            ['name' => 'Cook Islands', 'code' => 'COK'],
            ['name' => 'Niue', 'code' => 'NIU'],
            ['name' => 'Tokelau', 'code' => 'TKL'],
            ['name' => 'American Samoa', 'code' => 'ASM'],
            ['name' => 'French Polynesia', 'code' => 'PYF'],
            ['name' => 'Pitcairn', 'code' => 'PCN'],
            ['name' => 'Wallis and Futuna', 'code' => 'WLF'],
            ['name' => 'New Caledonia', 'code' => 'NCL'],
            ['name' => 'Norfolk Island', 'code' => 'NFK'],
            ['name' => 'Christmas Island', 'code' => 'CXR'],
            ['name' => 'Cocos Islands', 'code' => 'CCK'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HMD'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IOT'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'SGS'],
            ['name' => 'Falkland Islands', 'code' => 'FLK'],
            ['name' => 'Saint Helena', 'code' => 'SHN'],
            ['name' => 'Tristan da Cunha', 'code' => 'TAA'],
            ['name' => 'Ascension Island', 'code' => 'ASC'],
            ['name' => 'Bouvet Island', 'code' => 'BVT'],
            ['name' => 'French Southern Territories', 'code' => 'ATF'],
            ['name' => 'Antarctica', 'code' => 'ATA'],
            ['name' => 'Greenland', 'code' => 'GRL'],
            ['name' => 'Faroe Islands', 'code' => 'FRO'],
            ['name' => 'Iceland', 'code' => 'ISL'],
            ['name' => 'Norway', 'code' => 'NOR'],
            ['name' => 'Sweden', 'code' => 'SWE'],
            ['name' => 'Finland', 'code' => 'FIN'],
            ['name' => 'Denmark', 'code' => 'DNK'],
            ['name' => 'Estonia', 'code' => 'EST'],
            ['name' => 'Latvia', 'code' => 'LVA'],
            ['name' => 'Lithuania', 'code' => 'LTU'],
            ['name' => 'Belarus', 'code' => 'BLR'],
            ['name' => 'Moldova', 'code' => 'MDA'],
            ['name' => 'Slovakia', 'code' => 'SVK'],
            ['name' => 'Slovenia', 'code' => 'SVN'],
            ['name' => 'Croatia', 'code' => 'HRV'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH'],
            ['name' => 'Serbia', 'code' => 'SRB'],
            ['name' => 'Montenegro', 'code' => 'MNE'],
            ['name' => 'Kosovo', 'code' => 'XKX'],
            ['name' => 'North Macedonia', 'code' => 'MKD'],
            ['name' => 'Albania', 'code' => 'ALB'],
            ['name' => 'Portugal', 'code' => 'PRT'],
            ['name' => 'Switzerland', 'code' => 'CHE'],
            ['name' => 'Austria', 'code' => 'AUT'],
            ['name' => 'Liechtenstein', 'code' => 'LIE'],
            ['name' => 'Monaco', 'code' => 'MCO'],
            ['name' => 'Andorra', 'code' => 'AND'],
            ['name' => 'San Marino', 'code' => 'SMR'],
            ['name' => 'Vatican City', 'code' => 'VAT'],
            ['name' => 'Malta', 'code' => 'MLT'],
            ['name' => 'Cyprus', 'code' => 'CYP'],
            ['name' => 'Armenia', 'code' => 'ARM'],
            ['name' => 'Azerbaijan', 'code' => 'AZE'],
            ['name' => 'Georgia', 'code' => 'GEO'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ'],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ'],
            ['name' => 'Tajikistan', 'code' => 'TJK'],
            ['name' => 'Turkmenistan', 'code' => 'TKM'],
            ['name' => 'Uzbekistan', 'code' => 'UZB'],
            ['name' => 'Mongolia', 'code' => 'MNG'],
            ['name' => 'North Korea', 'code' => 'PRK'],
            ['name' => 'Taiwan', 'code' => 'TWN'],
            ['name' => 'Hong Kong', 'code' => 'HKG'],
            ['name' => 'Macau', 'code' => 'MAC'],
            ['name' => 'Guam', 'code' => 'GUM'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MNP'],
            ['name' => 'Puerto Rico', 'code' => 'PRI'],
            ['name' => 'U.S. Virgin Islands', 'code' => 'VIR'],
            ['name' => 'British Virgin Islands', 'code' => 'VGB'],
            ['name' => 'Cayman Islands', 'code' => 'CYM'],
            ['name' => 'Bermuda', 'code' => 'BMU'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TCA'],
            ['name' => 'Montserrat', 'code' => 'MSR'],
            ['name' => 'Anguilla', 'code' => 'AIA'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA'],
            ['name' => 'Antigua and Barbuda', 'code' => 'ATG'],
            ['name' => 'Dominica', 'code' => 'DMA'],
            ['name' => 'Saint Lucia', 'code' => 'LCA'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT'],
            ['name' => 'Grenada', 'code' => 'GRD'],
            ['name' => 'Barbados', 'code' => 'BRB'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO'],
            ['name' => 'Guyana', 'code' => 'GUY'],
            ['name' => 'Suriname', 'code' => 'SUR'],
            ['name' => 'French Guiana', 'code' => 'GUF'],
            ['name' => 'Belize', 'code' => 'BLZ'],
            ['name' => 'Guatemala', 'code' => 'GTM'],
            ['name' => 'El Salvador', 'code' => 'SLV'],
            ['name' => 'Honduras', 'code' => 'HND'],
            ['name' => 'Nicaragua', 'code' => 'NIC'],
            ['name' => 'Costa Rica', 'code' => 'CRI'],
            ['name' => 'Panama', 'code' => 'PAN'],
            ['name' => 'Cuba', 'code' => 'CUB'],
            ['name' => 'Jamaica', 'code' => 'JAM'],
            ['name' => 'Haiti', 'code' => 'HTI'],
            ['name' => 'Dominican Republic', 'code' => 'DOM'],
            ['name' => 'Bahamas', 'code' => 'BHS'],
            ['name' => 'Aruba', 'code' => 'ABW'],
            ['name' => 'Curaçao', 'code' => 'CUW'],
            ['name' => 'Sint Maarten', 'code' => 'SXM'],
            ['name' => 'Saint Martin', 'code' => 'MAF'],
            ['name' => 'Saint Barthélemy', 'code' => 'BLM'],
            ['name' => 'Guadeloupe', 'code' => 'GLP'],
            ['name' => 'Martinique', 'code' => 'MTQ'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'SPM'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BES'],
            ['name' => 'Saba', 'code' => 'SAB'],
            ['name' => 'Sint Eustatius', 'code' => 'EUX'],
            ['name' => 'Åland Islands', 'code' => 'ALA'],
            ['name' => 'Gibraltar', 'code' => 'GIB'],
            ['name' => 'Jersey', 'code' => 'JEY'],
            ['name' => 'Guernsey', 'code' => 'GGY'],
            ['name' => 'Isle of Man', 'code' => 'IMN'],
            ['name' => 'Ireland', 'code' => 'IRL'],
            ['name' => 'Luxembourg', 'code' => 'LUX'],
            ['name' => 'Isle of Wight', 'code' => 'IOW'],
            ['name' => 'Sark', 'code' => 'SRK'],
            ['name' => 'Herm', 'code' => 'HER'],
            ['name' => 'Alderney', 'code' => 'ALD'],
            ['name' => 'Brecqhou', 'code' => 'BRC'],
            ['name' => 'Jethou', 'code' => 'JTH'],
            ['name' => 'Lihou', 'code' => 'LIH'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Senegal', 'code' => 'SEN'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB'],
            ['name' => 'Cape Verde', 'code' => 'CPV'],
            ['name' => 'Gambia', 'code' => 'GMB'],
            ['name' => 'Mauritania', 'code' => 'MRT'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD'],
            ['name' => 'Sao Tome and Principe', 'code' => 'STP'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'Seychelles', 'code' => 'SYC'],
            ['name' => 'Comoros', 'code' => 'COM'],
            ['name' => 'Mayotte', 'code' => 'MYT'],
            ['name' => 'Réunion', 'code' => 'REU'],
            ['name' => 'Mauritius', 'code' => 'MUS'],
            ['name' => 'Madagascar', 'code' => 'MDG'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE'],
            ['name' => 'Mozambique', 'code' => 'MOZ'],
            ['name' => 'Eswatini', 'code' => 'SWZ'],
            ['name' => 'Lesotho', 'code' => 'LSO'],
            ['name' => 'Botswana', 'code' => 'BWA'],
            ['name' => 'Namibia', 'code' => 'NAM'],
            ['name' => 'South Africa', 'code' => 'ZAF'],
            ['name' => 'Israel', 'code' => 'ISR'],
            ['name' => 'Palestine', 'code' => 'PSE'],
            ['name' => 'Western Sahara', 'code' => 'ESH'],
            ['name' => 'Morocco', 'code' => 'MAR'],
            ['name' => 'Algeria', 'code' => 'DZA'],
            ['name' => 'Tunisia', 'code' => 'TUN'],
            ['name' => 'Libya', 'code' => 'LBY'],
            ['name' => 'Egypt', 'code' => 'EGY'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'South Sudan', 'code' => 'SSD'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'South Sudan', 'code' => 'SSD'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'South Sudan', 'code' => 'SSD'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'South Sudan', 'code' => 'SSD'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'South Sudan', 'code' => 'SSD'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'South Sudan', 'code' => 'SSD'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
        ];

        foreach ($countries as $country) {
            \App\Models\Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }
    }
}
